#!/bin/bash

# for loop

#dName=$1
#dCount=$2  # the number of tested directories that will be created
#fCount=$3  # the number of tested files that will be created for each tested directory

if test -d $1
then
	echo "The directory already exists, pls reinput and try again."
    exit 1
elif test -f $1
then
    echo "You input a file name but not a directory name,pls reinput and try again"
    exit 1
else
    mkdir $1
    cd    $1
fi




for (( i=1;i<=$2;i++)); do
	mkdir testedDir${i}
    cd    testedDir${i}

    for (( j=1;j<=$3;j++)); do

    	touch testedFile${j}
        echo  "This is a tested file generated by shell script!" > testedFile${j}

    done 

    cd ..


done 